curl_test.com mms1_aspoc_srvy_l2 yyyymmdd_rbsp /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_mms1_aspoc_srvy_l2_yyyymmdd_rbsp.xml
curl_test.com mms1_aspoc_srvy_l2 yyyymmdd_rbsp /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_mms1_aspoc_srvy_l2_yyyymmdd_rbsp.xml
curl_test.com mms1_aspoc_srvy_l2 yyyymmdd_rbsp /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_mms1_aspoc_srvy_l2_yyyymmdd_rbsp.xml
curl_test.com mms1_aspoc_srvy_l2 yyyymmdd_rbsp /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_mms1_aspoc_srvy_l2_yyyymmdd_rbsp.xml
curl_test.com mms1_aspoc_srvy_l2 yyyymmdd_rbsp /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_mms1_aspoc_srvy_l2_yyyymmdd_rbsp.xml
curl_test.com mms1_aspoc_srvy_l2 yyyymmdd_rbsp /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_mms1_aspoc_srvy_l2_yyyymmdd_rbsp.xml
curl_test.com mms1_aspoc_srvy_l2 yyyymmdd_rbsp /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_mms1_aspoc_srvy_l2_yyyymmdd_rbsp.xml
curl_test.com mms1_aspoc_srvy_l2 yyyymmdd_rbsp /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_mms1_aspoc_srvy_l2_yyyymmdd_rbsp.xml
curl_test.com mms1_aspoc_srvy_l2 yyyymmdd_rbsp /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_mms1_aspoc_srvy_l2_yyyymmdd_rbsp.xml
curl_test.com mms1_aspoc_srvy_l2 yyyymmdd_rbsp /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_mms1_aspoc_srvy_l2_yyyymmdd_rbsp.xml
curl_test.com mms1_aspoc_srvy_l2 yyyymmdd_rbsp /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_mms1_aspoc_srvy_l2_yyyymmdd_rbsp.xml
curl_test.com mms1_aspoc_srvy_l2 yyyymmdd_rbsp /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_mms1_aspoc_srvy_l2_yyyymmdd_rbsp.xml
curl_test.com mms1_aspoc_srvy_l2 yyyymmdd_rbsp /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_mms1_aspoc_srvy_l2_yyyymmdd_rbsp.xml
curl_test.com mms1_aspoc_srvy_l2 yyyymmdd_rbsp /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_mms1_aspoc_srvy_l2_yyyymmdd_rbsp.xml
curl_test.com mms1_aspoc_srvy_l2 yyyymmdd_rbsp /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_mms1_aspoc_srvy_l2_yyyymmdd_rbsp.xml
curl_test.com mms1_aspoc_srvy_l2 yyyymmdd_rbsp /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_mms1_aspoc_srvy_l2_yyyymmdd_rbsp.xml
curl_test.com mms1_aspoc_srvy_l2 yyyymmdd_rbsp /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_mms1_aspoc_srvy_l2_yyyymmdd_rbsp.xml
curl_test.com mms1_aspoc_srvy_l2 yyyymmdd_rbsp /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_mms1_aspoc_srvy_l2_yyyymmdd_rbsp.xml
curl_test.com mms1_aspoc_srvy_l2 yyyymmdd_rbsp /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_mms1_aspoc_srvy_l2_yyyymmdd_rbsp.xml
curl_test.com mms1_aspoc_srvy_l2 yyyymmdd_rbsp /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_mms1_aspoc_srvy_l2_yyyymmdd_rbsp.xml
curl_test.com mms1_aspoc_srvy_l2 yyyymmdd_rbsp /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_mms1_aspoc_srvy_l2_yyyymmdd_rbsp.xml
curl_test.com mms1_aspoc_srvy_l2 yyyymmdd_rbsp /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_mms1_aspoc_srvy_l2_yyyymmdd_rbsp.xml
curl_test.com mms1_aspoc_srvy_l2 yyyymmdd_rbsp /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_mms1_aspoc_srvy_l2_yyyymmdd_rbsp.xml
curl_test.com mms1_aspoc_srvy_l2 yyyymmdd_rbsp /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_mms1_aspoc_srvy_l2_yyyymmdd_rbsp.xml
curl_test.com mms1_aspoc_srvy_l2 yyyymmdd_rbsp /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_mms1_aspoc_srvy_l2_yyyymmdd_rbsp.xml
curl_test.com mms1_aspoc_srvy_l2 yyyymmdd_rbsp /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_mms1_aspoc_srvy_l2_yyyymmdd_rbsp.xml
curl_test.com mms1_aspoc_srvy_l2 yyyymmdd_rbsp /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_mms1_aspoc_srvy_l2_yyyymmdd_rbsp.xml
curl_test.com mms1_aspoc_srvy_l2 yyyymmdd_rbsp /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_mms1_aspoc_srvy_l2_yyyymmdd_rbsp.xml
curl_test.com mms1_aspoc_srvy_l2 yyyymmdd_rbsp /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_mms1_aspoc_srvy_l2_yyyymmdd_rbsp.xml
curl_test.com mms1_aspoc_srvy_l2 yyyymmdd_rbsp /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_mms1_aspoc_srvy_l2_yyyymmdd_rbsp.xml
curl_test.com mms1_aspoc_srvy_l2 yyyymmdd_rbsp /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_mms1_aspoc_srvy_l2_yyyymmdd_rbsp.xml
curl_test.com mms1_aspoc_srvy_l2 yyyymmdd_rbsp /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_mms1_aspoc_srvy_l2_yyyymmdd_rbsp.xml
curl_test.com mms1_aspoc_srvy_l2 yyyymmdd_rbsp /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_mms1_aspoc_srvy_l2_yyyymmdd_rbsp.xml
curl_test.com mms1_aspoc_srvy_l2 yyyymmdd_rbsp /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_mms1_aspoc_srvy_l2_yyyymmdd_rbsp.xml
curl_test.com mms1_aspoc_srvy_l2 yyyymmdd_rbsp /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_mms1_aspoc_srvy_l2_yyyymmdd_rbsp.xml
curl_test.com mms1_aspoc_srvy_l2 yyyymmdd_rbsp /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_mms1_aspoc_srvy_l2_yyyymmdd_rbsp.xml
curl_test.com mms1_aspoc_srvy_l2 yyyymmdd_rbsp /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_mms1_aspoc_srvy_l2_yyyymmdd_rbsp.xml
curl_test.com mms1_aspoc_srvy_l2 yyyymmdd_rbsp /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_mms1_aspoc_srvy_l2_yyyymmdd_rbsp.xml
curl_test.com mms1_aspoc_srvy_l2 yyyymmdd_rbsp /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_mms1_aspoc_srvy_l2_yyyymmdd_rbsp.xml
curl_test.com mms1_aspoc_srvy_l2 yyyymmdd_rbsp /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_mms1_aspoc_srvy_l2_yyyymmdd_rbsp.xml
curl_test.com mms1_aspoc_srvy_l2 yyyymmdd_rbsp /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_mms1_aspoc_srvy_l2_yyyymmdd_rbsp.xml
curl_test.com mms1_aspoc_srvy_l2 yyyymmdd_rbsp /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_mms1_aspoc_srvy_l2_yyyymmdd_rbsp.xml
curl_test.com mms1_aspoc_srvy_l2 yyyymmdd_rbsp /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_mms1_aspoc_srvy_l2_yyyymmdd_rbsp.xml
curl_test.com mms1_aspoc_srvy_l2 yyyymmdd_rbsp /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_mms1_aspoc_srvy_l2_yyyymmdd_rbsp.xml
curl_test.com mms1_aspoc_srvy_l2 yyyymmdd_rbsp /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_mms1_aspoc_srvy_l2_yyyymmdd_rbsp.xml
curl_test.com mms1_aspoc_srvy_l2 yyyymmdd_rbsp /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_mms1_aspoc_srvy_l2_yyyymmdd_rbsp.xml
curl_test.com mms1_aspoc_srvy_l2 yyyymmdd_rbsp /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_mms1_aspoc_srvy_l2_yyyymmdd_rbsp.xml
curl_test.com mms1_aspoc_srvy_l2 yyyymmdd_rbsp /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_mms1_aspoc_srvy_l2_yyyymmdd_rbsp.xml
curl_test.com mms1_aspoc_srvy_l2 yyyymmdd_rbsp /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_mms1_aspoc_srvy_l2_yyyymmdd_rbsp.xml
curl_test.com mms1_aspoc_srvy_l2 yyyymmdd_rbsp /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_mms1_aspoc_srvy_l2_yyyymmdd_rbsp.xml
curl_test.com mms1_aspoc_srvy_l2 yyyymmdd_rbsp /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_mms1_aspoc_srvy_l2_yyyymmdd_rbsp.xml
curl_test.com mms1_aspoc_srvy_l2 yyyymmdd_rbsp /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_mms1_aspoc_srvy_l2_yyyymmdd_rbsp.xml
curl_test.com mms1_aspoc_srvy_l2 yyyymmdd_rbsp /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_mms1_aspoc_srvy_l2_yyyymmdd_rbsp.xml
curl_test.com mms1_aspoc_srvy_l2 yyyymmdd_rbsp /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_mms1_aspoc_srvy_l2_yyyymmdd_rbsp.xml
curl_test.com mms1_aspoc_srvy_l2 yyyymmdd_rbsp /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_mms1_aspoc_srvy_l2_yyyymmdd_rbsp.xml
curl_test.com mms1_aspoc_srvy_l2 yyyymmdd_rbsp /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_mms1_aspoc_srvy_l2_yyyymmdd_rbsp.xml
curl_test.com mms1_aspoc_srvy_l2 yyyymmdd_rbsp /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_mms1_aspoc_srvy_l2_yyyymmdd_rbsp.xml
curl_test.com mms1_aspoc_srvy_l2 yyyymmdd_rbsp /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_mms1_aspoc_srvy_l2_yyyymmdd_rbsp.xml
curl_test.com mms1_aspoc_srvy_l2 yyyymmdd_rbsp /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_mms1_aspoc_srvy_l2_yyyymmdd_rbsp.xml
curl_test.com mms1_aspoc_srvy_l2 yyyymmdd_rbsp /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_mms1_aspoc_srvy_l2_yyyymmdd_rbsp.xml
curl_test.com mms1_aspoc_srvy_l2 yyyymmdd_rbsp /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_mms1_aspoc_srvy_l2_yyyymmdd_rbsp.xml
curl_test.com mms1_aspoc_srvy_l2 yyyymmdd_rbsp /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_mms1_aspoc_srvy_l2_yyyymmdd_rbsp.xml
curl_test.com mms1_aspoc_srvy_l2 yyyymmdd_rbsp /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_mms1_aspoc_srvy_l2_yyyymmdd_rbsp.xml
curl_test.com mms1_aspoc_srvy_l2 yyyymmdd_rbsp /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_mms1_aspoc_srvy_l2_yyyymmdd_rbsp.xml
curl_test.com mms1_aspoc_srvy_l2 yyyymmdd_rbsp /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_mms1_aspoc_srvy_l2_yyyymmdd_rbsp.xml
curl_test.com mms1_aspoc_srvy_l2 yyyymmdd_rbsp /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_mms1_aspoc_srvy_l2_yyyymmdd_rbsp.xml
curl_test.com mms1_aspoc_srvy_l2 yyyymmdd_rbsp /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_mms1_aspoc_srvy_l2_yyyymmdd_rbsp.xml
curl_test.com mms1_aspoc_srvy_l2 yyyymmdd_rbsp /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/CDAWEB/XML/cdaweb_mms1_aspoc_srvy_l2_yyyymmdd_rbsp.xml
